site_name: MaxGradient
repo_name: MaxGradient
repo_url: https://GitHub.com/maxludden/maxgradient
edit_uri: root/docs
site_description: Document MaxGradient, a python library built on the wonderful `rich` library that makes printing gradient colored text to the console easy.
site_author: Max Ludden
nav:
    - Getting Started: "index.md"
    - User Guide:
          - Console: "console.md"
          - Gradient: "gradient.md"
          - Color: "color.md"
    - References:
          - Console: "console_ref.md"
          - Gradient: "gradient_ref.md"
          - Color: "color_ref.md"

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - shell
    hljs_style: tokyo-night-dark
    logo: img/MaxGradient.svg
    include_homepage_in_sidebar: True
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.tracking
        - content.code.annotate
        - toc.integrate
        - toc.follow
        - navigation.path
        - navigation.top
        - content.code.copy
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

extra_css:
    - "styles/style.css"
    - "styles/purple.css"
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
