site_name: MaxGradient
repo_name: MaxGradient
repo_url: https://GitHub.com/maxludden/maxgradient
edit_uri: root/docs
site_description: Document MaxGradient, a python library built on the wonderful `rich` library that makes printing gradient colored text to the console easy.
site_author: Max Ludden
nav:
    - Home: "index.md"
    - User Guide:
        - Console: 'console.md'
        - Gradient: 'gradient.md'
        - Color: 'color.md'
    - References:
        - maxgradient.console.Console: 'console_ref.md'
        - maxgradient.color.Color: 'color_ref.md'
        - maxgradient.color_list.ColorList: color_list.md
        - Color: 'color_ref.md'
theme: 
    name: readthedocs
    logo: img/MaxGradient.svg
    include_homepage_in_sidebar: True
extra_css:
#   - "styles/gradient.css"
#   - "styles/next-btn.css"
#   - "styles/ref.css"