[project]
name = "MaxGradient"
directory = "/Users/maxludden/dev/MaxGradient"
version = "0.2.15"

[venv]
directory = "/Users/maxludden/dev/venvs/MaxGradient"
python = "/Users/maxludden/dev/venvs/MaxGradient/bin/python"

[time]
created=2021-03-03T15:00:00
modified=2023-12-28T04:23:00
