
[project]
name = "maxgradient"
version = "0.2.5"
description = "MaxGradient automates the printing gradient colored text to the console."
authors = [
    { name = "Max Ludden", email = "dev@maxludden.com" }
]
dependencies = [
    "rich>=13.5.3",
    "lorem-text>=2.1",
    "typer[all]>=0.9.0",
    "python-dotenv>=1.0.0",
    "loguru>=0.7.2",
    "PyYAML>=6.0.1",
    "sh>=2.0.6",
    "numpy>=1.25.2",
    "nptyping>=2.5.0",
    "pydantic>=2.5.0",
    "pendulum>=2.1.2",
    "ipython>=8.17.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "mkdocs>=1.5.2",
    "mkdocs-material>=9.4.7",
    "mkdocstrings[python]>=0.18",
    "snoop>=0.4.3",
    "cheap-repr>=0.5.1",
]

[tool.pdm.dependencies]
python = ">=3.10"
typer = { extras = ["all"], version = "^0.1.0" }

[tool.pdm.scripts]
gradient = { call = "maxgradient.cli:app" }

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

# Assume Python 3.8
target-version = "py38"

# Use the same default ignore list as Black.
ignore = [
    "E203",  # Whitespace before ':'
    "E501",  # Line too long
]

[[tool.mypy.overrides]]
module = 'maxgradient'
ignore_missing_imports = true


