
[project]
name = "MaxGradient"
version = "0.1.0"
description = "Scrape rochester, ny's craiglist for apartments and store in notion"
authors = [
    {name = "maxludden", email = "dev@maxludden.com"},
]
dependencies = [
    "loguru>=0.7.0",
    "rich>=13.4.2",
    "mkdocs>=1.4.3",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.scripts]
gradient = "maxgradient.cli.main:app"

[tool.pdm.hooks]
pre_debug = "pdm-hooks/pre_debug.py"

[tool.pdm.dev-dependencies]
dev = [
]
