
[project]
name = "gradient-cli"
version = "0.1.0"
description = "A CLI for maxludden/maxgradient"
authors = [
    { name = "maxludden", email = "dev@maxludden.com" },
    {name = "Max Ludden", email = "dev@maxludden.com"},
]
dependencies = [
    "rich>=13.5.3",
    "nptyping>=2.5.0",
    "numpy>=1.25.0",
    "lorem-text>=2.1",
    "typer[all]>=0.9.0",
    "python-dotenv[cli]>=1.0.0",
    "loguru>=0.7.2",
    "mongoengine>=0.27.0",
    "PyYAML>=6.0.1",
    "maxgradient>=0.1.9",
    "pydantic>=2.3.0",
    "sh>=2.0.6",
]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "mkdocs>=1.5.2",
]

[tool.pdm.dependencies]
python = ">=3.10"
typer = { extras = ["all"], version = "^0.1.0" }

[tool.pdm.scripts]
gradient = { call = "maxgradient.cli:app" }

[tool.pyright]
include = ["maxgradient"]
ignore = ["tests"]
pythonVersion = "3.11"
reportGeneralTypeIssues = false

[tool.pylint]
max-line-length = 120
disable = [
    "C0103",
    "C0301",
    "C0415",
    "E0001",
    "E0f04",
    "E0401",
    "E0611",
    "E1124",
    "W0012",
    "W0102",
    "W0612",
    "W0621",
    "W0201",
    "W0613",
    "W0622",
    "W0404",
    "R0903",
    "R0902",
    "R0912", 
    "R0913",
    "W0622",
    "W1401",
    "W0611",
    "W0212",
]
