# Generated by CodiumAI
from maxgradient.color import Color, ColorParseError
from maxgradient._mode import Mode
from maxgradient.gradient import Gradient
from lzma import MODE_FAST
from maxgradient._log import LogConsole
import unittest

class TestColor(unittest.TestCase):
        # Tests that a Gradient object can be created with default parameters
    def test_default_gradient(self):
        gradient = Gradient("Gradient Test")
        self.assertIsInstance(gradient, Gradient)
        self.assertEqual(gradient.hues, 3)
        self.assertEqual(len(gradient.colors), 3)
        
    # Tests that a Gradient object can be created with a custom mode
    def test_custom_mode(self):
        gradient = Gradient(
            "Test custom gradient!",
            colors=["#ff00ff", "#ff0000", "#ff8800"]
        )
    
    # Tests that a ColorParseError is raised when creating a Gradient object with an invalid color string
    def test_invalid_color_string(self):
        with self.assertRaises(ColorParseError):
            Gradient(text='Invalid', colors=['not a color'])

    # Tests that a ValueError is raised when creating a Gradient object with hues < 2
    def test_invalid_hues(self):
        with self.assertRaises(ValueError):
            Gradient(text='Invalid', hues=1)