"""Types for color_list.py"""
from typing import List

from rich.console import Console
from rich.table import Table
from rich.text import Text

from maxgradient.color import Color as Color
from maxgradient.log import Log as Log

console: Console
log: Log

class ColorList(list):
    colors: List[str]
    color_list: List[Color]
    def __init__(self, hues: int = ..., invert: bool = ...) -> None: ...
    def __call__(self): ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def reverse(self) -> None: ...
    def get_first_color(self) -> Color: ...
    def get_last_color(self) -> Color: ...
    @classmethod
    def colored_title(cls) -> Text: ...
    def __rich__(self) -> Table: ...

class TintList(List):
    tints: List[str]
    tint_list: List[Color]
    def __init__(self, hues: int = ..., invert: bool = ...) -> None: ...
    def __call__(self): ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def reverse(self) -> None: ...
    def get_first_color(self) -> Color: ...
    def get_last_color(self) -> Color: ...
    @classmethod
    def tint_title(cls) -> Text: ...
    def __rich__(self) -> Table: ...
