from maxgradient._console import Console as Console
from maxgradient.gradient import Gradient as Gradient
from maxgradient.rule import GradientRule as GradientRule
from rich.console import Group
from rich.panel import Panel
from typing import Iterable

TEXT: str

def gen_random_group() -> Group: ...
def gen_rainbow_group() -> Group: ...
def gen_red_orange_yellow_group() -> Group: ...
def gen_cool_group() -> Group: ...
def generate_panels() -> Iterable[Panel]: ...
def main() -> None: ...
