from maxgradient.color import Color as Color
from maxgradient.log import Log as Log
from rich.console import Console as Console
from rich.table import Table as Table
from rich.text import Text as Text
from typing import List

console: Console
log: Log

class ColorList(list):
    colors: List[str]
    color_list: List[Color]
    def __init__(self, hues: int = ..., invert: bool = ...) -> None: ...
    def __call__(self) -> None: ...
    def __getitem__(self, index) -> None: ...
    def __len__(self) -> int: ...
    def reverse(self) -> None: ...
    def get_first_color(self) -> Color: ...
    def get_last_color(self) -> Color: ...
    @classmethod
    def colored_title(cls) -> Text: ...
    def __rich__(self) -> Table: ...

class TintList(List):
    tints: List[str]
    tint_list: List[Color]
    def __init__(self, hues: int = ..., invert: bool = ...) -> None: ...
    def __call__(self) -> None: ...
    def __getitem__(self, index) -> None: ...
    def __len__(self) -> int: ...
    def reverse(self) -> None: ...
    def get_first_color(self) -> Color: ...
    def get_last_color(self) -> Color: ...
    @classmethod
    def tint_title(cls) -> Text: ...
    def __rich__(self) -> Table: ...
