from rich.style import Style as Style, StyleType as StyleType
from rich.table import Table as Table
from rich.text import Text as Text
from typing import Dict, Mapping

GRADIENT_STYLES: Mapping[str, StyleType]
EDITED_STYLES: Dict[str, str]

def get_default_styles() -> dict[str, Style]: ...
def formatted_title() -> Text: ...
def styles_table() -> Table: ...
def example() -> None: ...
